# stealc_gen_idc.py
# Run with: python stealc_gen_idc.py
# Requires: pip install pefile

from __future__ import annotations

import base64
import re
from typing import Optional

import pefile

# ── CONFIGURATION ──────────────────────────────────────────────────────────────
PE_PATH  = r"C:\Users\unina\Desktop\StealC\bin\stealc\Ida\cptchbuild.bin"   # path to your dumped PE
RC4_KEY  = b"rOIBXiPtf9"
OUT_IDC  = r"C:\Users\unina\Desktop\StealC\bin\stealc\Ida\stealc_annotate.idc"
OUT_TXT  = r"C:\Users\unina\Desktop\StealC\bin\stealc\Ida\stealc_strings.txt"
# ──────────────────────────────────────────────────────────────────────────────


def rc4_decrypt(key: bytes, data: bytes) -> bytes:
    sbox = list(range(256))
    j = 0

    for i in range(256):
        j = (j + sbox[i] + key[i % len(key)]) & 0xFF
        sbox[i], sbox[j] = sbox[j], sbox[i]

    i = 0
    j = 0
    out = bytearray()
    for byte in data:
        i = (i + 1) & 0xFF
        j = (j + sbox[i]) & 0xFF
        sbox[i], sbox[j] = sbox[j], sbox[i]
        out.append(byte ^ sbox[(sbox[i] + sbox[j]) & 0xFF])

    return bytes(out)


def try_decrypt(blob: bytes) -> Optional[str]:
    try:
        # Pad to valid Base64 length and reject malformed alphabet mixes.
        pad = (4 - len(blob) % 4) % 4
        raw = base64.b64decode(blob + b"=" * pad, validate=True)
        if not raw:
            return None
        plain = rc4_decrypt(RC4_KEY, raw)
        # Accept only printable ASCII (StealC strings are always ASCII)
        text = plain.rstrip(b"\x00")
        if not text:
            return None
        decoded = text.decode("utf-8", errors="replace")
        if all(0x20 <= ord(c) < 0x7F or c in "\t\n\r" for c in decoded):
            return decoded
    except Exception:
        pass
    return None


def escape_idc_text(text: str) -> str:
    escaped = []
    for ch in text:
        code_point = ord(ch)
        if ch == "\\":
            escaped.append("\\\\")
        elif ch == '"':
            escaped.append('\\"')
        elif ch == "\n":
            escaped.append("\\n")
        elif ch == "\r":
            escaped.append("\\r")
        elif ch == "\t":
            escaped.append("\\t")
        elif 0x20 <= code_point <= 0x7E:
            escaped.append(ch)
        else:
            escaped.append(f"\\x{code_point:02X}")
    return "".join(escaped)


def safe_name(text: str, max_len: int = 48) -> str:
    sanitized = re.sub(r"[^A-Za-z0-9]", "_", text)[:max_len].strip("_")
    return "str_" + sanitized if sanitized else "str_blob"


def unique_name(text: str, va: int) -> str:
    base_name = safe_name(text)
    return f"{base_name}_{va:X}"


def main():
    pe = pefile.PE(PE_PATH)
    image_base = pe.OPTIONAL_HEADER.ImageBase

    # Find .rdata section
    rdata_section = next(
        (s for s in pe.sections if b".rdata" in s.Name), None
    )
    if not rdata_section:
        print("[!] .rdata section not found — trying .data")
        rdata_section = next(
            (s for s in pe.sections if b".data" in s.Name), None
        )
    if not rdata_section:
        raise RuntimeError("Cannot locate a data section")

    section_data = rdata_section.get_data()
    section_va   = image_base + rdata_section.VirtualAddress
    section_name = rdata_section.Name.rstrip(b"\x00").decode(errors="replace")

    print(f"[*] Scanning {section_name} "
          f"({len(section_data):,} bytes) at VA 0x{section_va:X}")

    # Match Base64 blobs only when they are not embedded inside a larger token.
    pattern = re.compile(rb"(?<![A-Za-z0-9+/])[A-Za-z0-9+/]{8,}={0,2}(?![A-Za-z0-9+/=])")

    results: list[tuple[int, str, str]] = []
    seen_vas: set[int] = set()

    for match in pattern.finditer(section_data):
        blob    = match.group()
        va      = section_va + match.start()
        if va in seen_vas:
            continue
        plaintext = try_decrypt(blob)
        if plaintext:
            seen_vas.add(va)
            results.append((va, blob.decode(), plaintext))

    if not results:
        print("[!] No strings decrypted — check PE path, key, and function address")
        return

    results.sort(key=lambda x: x[0])
    print(f"[+] Decrypted {len(results)} strings\n")

    # ── Write plain text list ──────────────────────────────────────────────────
    with open(OUT_TXT, "w", encoding="utf-8") as f:
        f.write(f"StealC decrypted strings - RC4 key: {RC4_KEY.decode()}\n")
        f.write("=" * 60 + "\n\n")
        for va, blob, plain in results:
            print(f"  0x{va:X}  ->  {plain!r}")
            f.write(f"0x{va:016X}  {plain}\n")
    print(f"\n[+] String list saved: {OUT_TXT}")

    # ── Generate IDC annotation script ────────────────────────────────────────
    idc_lines = [
        '#include <idc.idc>',
        '',
        '// Auto-generated by stealc_gen_idc.py',
        f'// RC4 key: {RC4_KEY.decode()}',
        f'// Source: {PE_PATH}',
        '',
        'static main() {',
        f'    Message("Applying {len(results)} StealC string annotations...\\n");',
        '',
    ]

    for va, blob, plain in results:
        # Escape control characters and quotes for IDC string literals.
        plain_escaped = escape_idc_text(plain)
        name_safe     = unique_name(plain, va)

        idc_lines.append(f'    // {plain_escaped[:80]}')
        idc_lines.append(f'    MakeName(0x{va:X}, "{name_safe}");')
        idc_lines.append(f'    MakeComm(0x{va:X}, "DECRYPTED: \\"{plain_escaped}\\"");')
        idc_lines.append('')

    idc_lines += [
        f'    Message("[+] Done - {len(results)} strings annotated.\\n");',
        '}',
    ]

    with open(OUT_IDC, "w", encoding="utf-8") as f:
        f.write("\n".join(idc_lines))
    print(f"[+] IDC script saved: {OUT_IDC}")
    print(f"    → Load it in IDA Free via File → Script File")


if __name__ == "__main__":
    main()